In [9]:
import pyspedas
import pytplot
from pytplot import options
from pytplot import tplot
from pytplot import tlimit
from pytplot import tplot_options
from load import mca, orb
import numpy as np
import Akebono_orb_load 
importer = Akebono_orb_load.Akebono_orb_load('19910711')

In [10]:
trange = ['1991-07-11', '1991-07-13']
mca(trange=trange)
importer.orb()


Time clip returns full data set.
Time clip returns full data set.
Time clip returns full data set.
Time clip returns full data set.
Time clip returns full data set.


In [11]:
pytplot.tplot_names()

0 : Emax
1 : Eave
2 : Bmax
3 : Bave
4 : PostGap
5 : akb_orb_Pass
6 : akb_orb_ILAT
7 : akb_orb_MLT
8 : akb_orb_ALT


['Emax',
 'Eave',
 'Bmax',
 'Bave',
 'PostGap',
 'akb_orb_Pass',
 'akb_orb_ILAT',
 'akb_orb_MLT',
 'akb_orb_ALT']

In [13]:
Pass = pytplot.get_data('akb_orb_Pass')
Pass.y

array([9.1071007e+09, 9.1071100e+09, 9.1071100e+09, ..., 9.1071107e+09,
       9.1071107e+09, 9.1071107e+09])

In [14]:
import numpy as np

a = np.arange(9).reshape((3, 3))
print(a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
np.where(a < 5)

(array([0, 0, 0, 1, 1]), array([0, 1, 2, 0, 1]))

In [17]:
list(zip(*np.where(a < 4)))

[(0, 0), (0, 1), (0, 2), (1, 0)]

In [21]:
times = np.arange(10)
data = np.arange(5)
data, times

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [25]:
pytplot.store_data('tinterpol_test', data = {'x': times, 'y': times})
pytplot.store_data('tinterpol_test1', data = {'x': data, 'y': data})
pytplot.tplot_names()

0 : Emax
1 : Eave
2 : Bmax
3 : Bave
4 : PostGap
5 : akb_orb_Pass
6 : akb_orb_ILAT
7 : akb_orb_MLT
8 : akb_orb_ALT
9 : titnerpol_test
10 : tinterpol_test1
11 : tinterpol_test


['Emax',
 'Eave',
 'Bmax',
 'Bave',
 'PostGap',
 'akb_orb_Pass',
 'akb_orb_ILAT',
 'akb_orb_MLT',
 'akb_orb_ALT',
 'titnerpol_test',
 'tinterpol_test1',
 'tinterpol_test']

In [26]:
pyspedas.tinterpol('tinterpol_test1', interp_to='tinterpol_test')

tinterpol (linear) was applied to: tinterpol_test1-itrp
