In [1]:
import numpy as np

a = np.arange(9).reshape((3, 3))
print(a)

np.where(a < 5)
list(zip(*np.where(a < 4)))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [5]:
import pytplot, pyspedas
from pytplot import tplot
times = np.arange(10)
data = np.arange(0,10, 2)
data, times
pytplot.store_data('tinterpol_test', data = {'x': times, 'y': times})
pytplot.store_data('tinterpol_test1', data = {'x': data, 'y': data})
pytplot.tplot_names()

0 : tinterpol_test
1 : tinterpol_test1
2 : tinterpol_test1-itrp


['tinterpol_test', 'tinterpol_test1', 'tinterpol_test1-itrp']

In [6]:
pyspedas.tinterpol('tinterpol_test1', interp_to='tinterpol_test')

tinterpol (linear) was applied to: tinterpol_test1-itrp


In [10]:
x = pytplot.get_data('tinterpol_test')
y = pytplot.get_data('tinterpol_test1-itrp')
z = pytplot.get_data('tinterpol_test1')

In [11]:
x,y,z

(variable(times=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), y=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])),
 variable(times=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), y=array([ 0.,  1.,  2.,  3.,  4., nan, nan, nan, nan, nan])),
 variable(times=array([0, 1, 2, 3, 4]), y=array([0, 1, 2, 3, 4])))